services:
  database:
    build: ./integrated-1-database
    container_name: database
    restart: unless-stopped
    networks:
      - integrated_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./integrated-1-backend
    container_name: backend
    restart: unless-stopped
    networks:
      - integrated_net
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_NAME=integrated
      - DB_USER=dev
      - DB_PASS=Mysql@sit123

  frontend:
    build: ./integrated-1-frontend
    container_name: frontend
    restart: unless-stopped
    networks:
      - integrated_net
    depends_on:
      - backend
  
  proxy:
    build: ./integrated-1-proxy
    container_name: proxy
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - integrated_net
    depends_on:
      - frontend
      - backend
      - database

networks:
  integrated_net:

