services:
  database:
    build: ./integrated-1-database
    container_name: database
    restart: unless-stopped
    networks:
      - integrated_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./integrated-1-backend
    container_name: backend
    restart: unless-stopped
    networks:
      - integrated_net
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - WEB_HOST=https://intproj23.sit.kmutt.ac.th/sj1/
    env_file:
      - ./integrated-1-backend/.env

  frontend:
    build: ./integrated-1-frontend
    container_name: frontend
    restart: unless-stopped
    networks:
      - integrated_net
    depends_on:
      - backend

  proxy:
    build: ./integrated-1-proxy
    container_name: proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - integrated_net
    depends_on:
      - frontend
      - backend
      - database
    volumes:
      - /home/sysadmin/deploy/integrated-1-proxy/ssl:/ssl
      
networks:
  integrated_net:
