version: '3.7'

services:
  database:
    build: ./integrated-1-database
    container_name: database
    # ports:
    #   - '3306:3306'
    networks:
      - backend_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./integrated-1-backend
    container_name: backend
    restart: always
    ports:
      - '8080:8080'
    networks:
      - backend_net
      - frontend_net
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_NAME=integrated
      - DB_USER=dev
      - DB_PASS=Mysql@sit123

  frontend:
    build: ./integrated-1-frontend
    container_name: frontend
    ports:
      - 80:80
    networks:
      - frontend_net
    depends_on:
      - backend

networks:
  backend_net:
  frontend_net:
