version: '3'

services:

  database:
    container_name: database
    image: mysql/mysql-server
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: integrated
      MYSQL_ROOT_PASSWORD: mysql@sit
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      
  backend:
    build: ./integrated-1-backend
    ports:
      - "8080:8080"
    depends_on:
      - database

  frontend:
    build: ./integrated-1-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  
